// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB1esfyGdA7K2bqQOFcpArdiISeg40BKQ',
    appId: '1:1066387393535:web:50d2e6f8a8762b9eaeb5ca',
    messagingSenderId: '1066387393535',
    projectId: 'trai-flutter-demo',
    authDomain: 'trai-flutter-demo.firebaseapp.com',
    storageBucket: 'trai-flutter-demo.firebasestorage.app',
    measurementId: 'G-4K0JC09QSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaPOmf9lVGoOGhKKceRTjCT5TcJdIj5dM',
    appId: '1:1066387393535:android:0be6a95efd3b3047aeb5ca',
    messagingSenderId: '1066387393535',
    projectId: 'trai-flutter-demo',
    storageBucket: 'trai-flutter-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASeRLG7ddu0hPfh9ik42rQMbFrwKPw0g4',
    appId: '1:1066387393535:ios:27089f2829ca5382aeb5ca',
    messagingSenderId: '1066387393535',
    projectId: 'trai-flutter-demo',
    storageBucket: 'trai-flutter-demo.firebasestorage.app',
    iosBundleId: 'com.trai.ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASeRLG7ddu0hPfh9ik42rQMbFrwKPw0g4',
    appId: '1:1066387393535:ios:c3a91643bfc7c668aeb5ca',
    messagingSenderId: '1066387393535',
    projectId: 'trai-flutter-demo',
    storageBucket: 'trai-flutter-demo.firebasestorage.app',
    iosBundleId: 'com.example.traiNewUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB1esfyGdA7K2bqQOFcpArdiISeg40BKQ',
    appId: '1:1066387393535:web:8770dfd270debee7aeb5ca',
    messagingSenderId: '1066387393535',
    projectId: 'trai-flutter-demo',
    authDomain: 'trai-flutter-demo.firebaseapp.com',
    storageBucket: 'trai-flutter-demo.firebasestorage.app',
    measurementId: 'G-PSXG3NNY1F',
  );
}
